#!/bin/bash
# capture_env.sh — snapshot everything needed to reproduce a run.
#
# WHY. T0.1 of paper/PLAN.md: until this exists, "we ran method X and it was a wash" is unfalsifiable,
# because nobody -- including us after a disk failure -- can establish WHAT was run. A results log
# without a matching environment is a claim, not a record.
#
# Writes a dated snapshot to paper/env/ (tracked). Run it before any campaign whose numbers will be
# published, and cite the snapshot filename in the results entry.
#
#   ./tools/capture_env.sh              # -> paper/env/env-YYYY-MM-DD.md
#   OUT=paper/env/env-preflight.md ./tools/capture_env.sh
set -u
cd "$(dirname "${BASH_SOURCE[0]}")/.." || exit 1
OUT=${OUT:-paper/env/env-$(date +%F).md}
mkdir -p "$(dirname "$OUT")"
PY=${PY:-./.venv/bin/python}

{
echo "# Environment snapshot — $(date -u +'%Y-%m-%d %H:%M:%S UTC')"
echo
echo "Generated by \`tools/capture_env.sh\`. Cite this filename in any results entry it backs."
echo
echo '## Repository'
echo '```'
echo "commit      $(git rev-parse HEAD 2>/dev/null)"
echo "branch      $(git rev-parse --abbrev-ref HEAD 2>/dev/null)"
echo "describe    $(git describe --always --dirty --tags 2>/dev/null)"
# A dirty tree means the snapshot does not fully describe the code that ran. Say so loudly.
if [ -n "$(git status --porcelain 2>/dev/null)" ]; then
  echo "tree        DIRTY — uncommitted changes present, snapshot is INCOMPLETE:"
  git status --porcelain | sed 's/^/              /'
else
  echo "tree        clean"
fi
echo '```'
echo
echo '## Host'
echo '```'
echo "kernel      $(uname -sr)"
echo "cpu         $(grep -m1 'model name' /proc/cpuinfo | cut -d: -f2- | sed 's/^ //')"
echo "cores       $(nproc)"
echo "ram         $(free -g | awk '/^Mem:/{print $2" GiB"}')"
echo "numa nodes  $(lscpu 2>/dev/null | awk -F: '/NUMA node\(s\)/{gsub(/ /,"",$2);print $2}')"
echo "avx2        $(grep -qm1 avx2 /proc/cpuinfo && echo yes || echo 'NO (AVX only)')"
echo "disk free   $(df -h . | awk 'NR==2{print $4}')"
echo '```'
echo
echo '## GPU'
echo '```'
nvidia-smi --query-gpu=index,name,memory.total,driver_version --format=csv 2>/dev/null || echo "nvidia-smi unavailable"
echo '```'
echo
echo '## Python / CUDA'
echo '```'
$PY -c "
import torch, platform
print('python      ' + platform.python_version())
print('torch       ' + torch.__version__)
print('cuda        ' + str(torch.version.cuda))
print('cudnn       ' + str(torch.backends.cudnn.version()))
print('devices     ' + str(torch.cuda.device_count()))
" 2>/dev/null || echo "torch import failed"
echo '```'
echo
echo '## Key package versions'
echo '```'
$PY -m pip freeze 2>/dev/null | grep -iE '^(torch|transformers|datasets|accelerate|safetensors|numpy|tokenizers|huggingface|sentencepiece|lm[-_]eval)' || echo "pip freeze failed"
echo '```'
echo
echo '## Dataset revisions'
echo
echo 'Datasets are pinned by HF cache commit. A benchmark that silently changes revision between arms'
echo 'destroys pairing, so these hashes belong in the record.'
echo '```'
for d in "$HOME"/.cache/huggingface/hub/datasets--*; do
  [ -d "$d" ] || continue
  name=$(basename "$d" | sed 's/^datasets--//; s/--/\//')
  rev=$(ls "$d/snapshots" 2>/dev/null | head -1)
  printf '%-40s %s\n' "$name" "${rev:-<no snapshot>}"
done
echo '```'
echo
echo '## Model revisions'
echo '```'
for d in "$HOME"/.cache/huggingface/hub/models--*; do
  [ -d "$d" ] || continue
  name=$(basename "$d" | sed 's/^models--//; s/--/\//')
  rev=$(ls "$d/snapshots" 2>/dev/null | head -1)
  printf '%-40s %s\n' "$name" "${rev:-<no snapshot>}"
done
echo '```'
echo
echo '## Pipeline constants'
echo
echo 'CAUTION: `src/config.py` binds model geometry at IMPORT time from `ORIG_MODEL`. The values below'
echo 'are therefore whatever `ORIG_MODEL` pointed at when this snapshot ran -- NOT a property of the'
echo 'repository. To describe a specific run, set the same `ORIG_MODEL` this script saw. The env vars'
echo 'are listed underneath precisely so the constants can be interpreted.'
echo '```'
$PY -c "
import sys; sys.path.insert(0,'src')
import config
for k in ('BLOCK_SIZE','NUM_HIDDEN_LAYERS'):
    print(f'{k:24s} {getattr(config,k,\"<absent>\")}')
" 2>/dev/null || echo "config import failed"
echo '```'
echo
echo 'Environment variables that change the above, or change run semantics:'
echo '```'
for v in ORIG_MODEL MODEL_4B MODEL_27B TERNARY_BLOCK_SIZE REPO_ROOT CUDA_VISIBLE_DEVICES \
         DENSE_INFER HEAD_MODE EMBED_MODE DRY_MULT THINK_ROW_SCALE N_SCORE SCORE_MAXNEW \
         TEACHER_THINK_LEN SEED PYTORCH_CUDA_ALLOC_CONF; do
  printf '%-24s %s\n' "$v" "${!v:-<unset>}"
done
echo '```'
} > "$OUT"

echo "wrote $OUT"
grep -q "DIRTY" "$OUT" && echo "WARNING: working tree is dirty — this snapshot does not fully describe the code."
exit 0
